name: Check Astro

on: pull_request

jobs:
  check-astro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependecies
        run: bun install
      - name: Astro check
        run: bun run check
      - name: Astro build
        run: bun run build
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress **/*.md **/*.html **/*.css **/*.ts **/*.tsx
          fail: true
