name: Update packages

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#00_06_*_*_1
    # "At 06:00 on Monday"
    - cron: "00 06 * * 1"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name:
        run: bun x npm-check-updates -u
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          create_branch: true
          commit_message: 🤖 Autoupdate packages
          branch: update-packages
      - name: Create Pull Request
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "🤖 Autoupdate packages"
          body: |
            Update package.json
            - Auto-generated by [update_packages][1]

            [1]: https://github.com/josetorronteras/josetorronteras.github.io/blob/main/.github/workflows/cron-update-packages.yml
          labels: |
            automated
            dependencies
