name: Lychee Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#00_07_*_*_1
    # "At 07:00 on Monday"
    - cron: "00 07 * * 1"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependecies
        run: bun install
      - name: Astro build
        run: bun run build
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --exclude-path node_modules --no-progress **/*.md **/*.html **/*.css **/*.ts **/*.tsx
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
