name: Autocode formatter

on: pull_request

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependecies
        run: bun install
      - name: Launch Prettier
        run: bun run prettier --check --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Code formatter (Prettier)
